rrdtool-enh: Implemented install/uninstall/gauge/sample.

diff --git a/toolenh/rrdtool-enh/shlib.d/rrdwrapper b/toolenh/rrdtool-enh/shlib.d/rrdwrapper
--- a/toolenh/rrdtool-enh/shlib.d/rrdwrapper
+++ b/toolenh/rrdtool-enh/shlib.d/rrdwrapper
@@ -1,11 +1,15 @@
 # vim: set filetype=sh :
 
+    SCRIPT_PATH=`readlink -f $0`
+
     import cliboot
+    import time
 
     option -i --install     "Create an rrd database and setup crons"
     option    --remove      "Delete an rrd database and remove crons"
-    option -r --run-cron =ID "Run the specific cron job"
-    option    --run-all     "Run all cron jobs immediately"
+    option    --run =ID "Run the specific sample procedure immediately"
+    option -r --run-cron =ID "Run the specific sample procedure from cron"
+    option    --run-all     "Run all sample procedures immediately"
     option -l --list        "List available graphs"
     option -p --plot =ID    "Plot the specific graph"
     option    --plot-all    "Plot all graphs"
@@ -18,9 +22,19 @@
 
     MODE=run-all
     CGI=0
-    job_id=
+    cron_mode=0
+
+    rcfile="$HOME/.rrdwrapper.rc"
+    datadir="$HOME/public/data"
+    plotdir="$HOME/public/html/plots"
+    datafile=
+    plotout=
+
+    run_id=
     plot_id=
     content_type=
+
+    pending_cmdv=()
 
 function setopt() {
     case "$1" in
@@ -28,9 +42,13 @@ function setopt() {
             MODE=install;;
         --remove)
             MODE=remove;;
+        --run)
+            MODE=run
+            run_id="$2";;
         -r|--run-cron)
-            MODE=run-cron
-            job_id="$2";;
+            MODE=run
+            run_id="$2"
+            cron_mode=1;;
         --run-all)
             MODE=run-all;;
         -l|--list)
@@ -61,13 +79,35 @@ function main() {
     [ -n "$REMOTE_ADDR" ] && CGI=1
 
     # initialization...
+    if [ -f "$rcfile" ]; then
+        . "$rcfile" || die "Failed to init rrdwrapper rc file, exit code=$?"
+    fi
+
+    trap 'commit' EXIT
 }
 
-boot "$@"
+function commit() {
+    [ ${#pending_cmdv[@]} = 0 ] && return
+
+    _log2 "Commit pending command: ${pending_cmdv[@]}"
+    if "${pending_cmdv[@]}"; then
+        _log2 "Succeeded."
+    else
+        _error "Failed: exit code=$?"
+    fi
+}
+
+function pendemit() {
+    local arg
+    local n=${#pending_cmdv[@]}
+    for arg in "$@"; do
+        pending_cmdv[n++]="$arg"
+    done
+}
 
 # RRD Wrapper Framework:
-
-job_id=
+topic=no-database
+step_time=300
 
 plot_index=0
 current_plot_id=default
@@ -78,32 +118,204 @@ plotcmds=()
 plotcmdn=0
 
 function database() {
+    topic="$1"
+    datafile="$datadir/${topic}_db.rdb"
+    shift
+
     case "$MODE" in
-    install)
-        ;;
-    remove)
-        ;;
+        install)
+            mkdir -p "$datadir"
+            pending_cmdv=(rrdtool create "$datafile")
+
+            while parse_event "$@"; do
+                case "${ACTION[0]}" in
+                    step) # on 60sec step
+                        step_time=`duration2sec $EVENT`
+                        pendemit --step $step_time
+                        ;;
+
+                    make) # on 1step make max for 30day
+                        local unit=`getunit $EVENT`
+                        local steps=
+                        if [ "$unit" = step ]; then
+                            steps=${EVENT:0: -4}
+                        else
+                            steps=`duration2sec $EVENT`
+                            steps=$(( steps / step_time ))
+                        fi
+
+                        [ "${ACTION[2]}" = "for" ] || die "Expected 'for': ${ACTION[2]}"
+
+                        local target="${ACTION[1]}"
+
+                        local for_time="${ACTION[3]}"
+                        local for_steps=
+                        unit=`getunit $for_time`
+                        if [ "$unit" = step ]; then
+                            for_steps=${for_time:0: -4}
+                        else
+                            for_steps=`duration2sec $for_time`
+                            for_steps=$(( for_steps / step_time ))
+                        fi
+
+                        case "$target" in
+                            max)
+                                target=MAX;;
+                            min)
+                                target=MIN;;
+                            average)
+                                target=AVERAGE;;
+                            last)
+                                target=LAST;;
+                            *)
+                                die "Illegal RRD archive: $target";;
+                        esac
+
+                        pendemit RRA:$target:0.5:$steps:$for_steps
+                        ;;
+                esac
+                shift $NEXT_ON
+            done
+
+            ;;
+
+        remove)
+            _log1 "Remove the RRD database $datafile."
+            rm -f "$datafile"
+            ;;
     esac
 }
 
 function gauge() {
+    local id="$1"
+    local range="$2"
+    shift 2
+
+    local timeout=$step_time
+    while parse_event "$@"; do
+        case "${ACTION[0]}" in
+            timeout) # on 10min timeout
+                timeout=`duration2sec $EVENT`
+                ;;
+            read) # on pingtest read RTT_AVG
+                local sample_id="$EVENT"
+                local reffield="${ACTION[1]}"
+                local cmap_var=cmap_${sample_id}
+
+                # NOT WORKED.
+                #Segment fault: if declare a local assoc array here.
+                #[ -v "$cmap_var" ] || declare -g -A $cmap_var
+                #declare "${cmap_var}[$id]"="$reffield"
+
+                # Append ":rtt=RTT_AVG" to cmap.
+                declare -g $cmap_var="${!cmap_var}:$id=$reffield"
+                ;;
+        esac
+        shift $NEXT_ON
+    done
+
     case "$MODE" in
-    install) # Define RRA records
-        ;;
-    run-cron) # On job done, do update
-        ;;
+        install) # Define RRA records
+            pendemit "DS:$id:GAUGE:$timeout:$range"
+            ;;
+
+        run) # On job done, do update
+            : # executed by "sample" statement.
+            ;;
     esac
 }
 
-function cron() {
+function sample() {
+    local id="$1"; shift
+    local interval
+    local crontab
+    local cron_id="@RRD $topic::$id"
+
+    while parse_event "$@"; do
+        case "${ACTION[0]}" in
+            update) # on 3min update
+                interval=`duration2sec $EVENT`;;
+            *)
+                die "Unexpected: $@";;
+        esac
+        shift $NEXT_ON
+    done
+
     case "$MODE" in
-    install) # Install crontab
-        ;;
-    remove) # Uninstall crontab
-        ;;
-    run-cron) # Run the command
-        ;;
+        install) # Install crontab
+            local cronspec="* * * * *" # Ignore interval.
+
+            crontab=`tempfile`
+            crontab -l >$crontab
+
+            lineconf -tm "Add sample procedure to crontab" \
+                $crontab "$cron_id" \
+                "$cronspec \"$SCRIPT_PATH\" --run \"$id\""
+
+            crontab $crontab
+            rm -f $crontab
+            ;;
+
+        remove) # Uninstall crontab
+            _log1 "Remove sample procedure from crontab."
+
+            crontab=`tempfile`
+            crontab -l >$crontab
+
+            lineconf -k $crontab "$cron_id"
+
+            crontab $crontab
+            rm -f $crontab
+            ;;
+
+        run) # Run the command
+            if [ "$run_id" = "$id" ]; then
+                local run_now=1
+                if [ "$cron_mode" = 1 ]; then
+                    local time_m=$(( `date +$s` / 60 )) # minutes since 1970-1-1
+                    local interval_m=$(( interval / 60 ))
+                    local offset=$(( time_m % interval_m ))
+                    run_now=$(( offset == 0 ))
+                fi
+                if [ "$run_now" = 1 ]; then
+                    _log2 "Add sample-execution to the cmdqueue: $id"
+                    pendemit sample_exec "$id" # TODO Add custom arguments support?
+                fi
+            fi
+            ;;
     esac
+}
+
+function sample_exec() {
+    local id="$1"; shift
+    local cmap_var=cmap_$id
+    local output=`tempfile`
+
+    if "${id}_proc" "$@" >$output; then
+        _log2 "Succeeded to execute the sample procedure."
+
+        local key val
+        while IFS== read key val; do
+            declare "val_$key"="$val"
+            _log2 "Field $key = $val"
+        done <$output
+
+        local cmap="${!cmap_var}"
+        local entry
+        for entry in ${cmap//:/ }; do
+            [ -z "$entry" ] && continue
+            local vname="${entry%%=*}"
+            local fieldvar="val_${entry#*=}"
+            val="${!fieldvar}"
+            _log1 "Update data source $vname to $val"
+
+            rrdtool update "$datafile" --template "$vname" N:"$val"
+        done
+    else
+        _error "Failed to execute the sample procedure, exit code=$?"
+    fi
+
+    rm -f $output
 }
 
 function graph() {
@@ -113,27 +325,29 @@ function graph() {
     (( plot_index++ ))
 
     case "$MODE" in
-    list)
-        #if [ "$CGI" = 0 ]; then
-            echo -n "Graph $plot_index. $1"
-            if [ $# = 0 ]; then
-                echo
-            else
-                echo ": $*"
-            fi
-        #fi
-        ;;
+        list)
+            #if [ "$CGI" = 0 ]; then
+                echo -n "Graph $plot_index. $id"
+                if [ $# = 0 ]; then
+                    echo
+                else
+                    echo ": $*"
+                fi
+            #fi
+            ;;
 
-    plot-all)
-        _log1 "Plot-Graph: $id"
-        "$PROGRAM" --plot "$id"
-        ;;
+        plot-all)
+            _log1 "Plot-Graph: $id"
+            "$SCRIPT_PATH" --plot "$id"
+            ;;
 
-    plot)
-        current_plot_id="$1"
-        plot_opts=()
-        plot_optn=0
-        ;;
+        plot)
+            current_plot_id="$1"
+            plot_opts=()
+            plot_optn=0
+
+            mkdir -p "$plotdir" || die "Failed to create plotdir $plotdir"
+            ;;
     esac
 }
 
@@ -146,17 +360,17 @@ function isplot() {
 function plot-config() {
     isplot || return
     plot_opts=("$@")
-    plot_optn="${#plot_opts}"
+    plot_optn="${#plot_opts[@]}"
 }
 
-function emit() {
+function plotemit() {
     local arg
     for arg in "$@"; do
         plotcmds[plotcmdn++]="$arg"
     done
 }
 
-function emitdef() {
+function plotemitdef() {
     local deftype="$1"
     shift
 
@@ -168,32 +382,32 @@ function emitdef() {
     expr="${expr# }"
 
     expr=`rpn_eval $expr`
-    emit "$deftype:$vname:$expr"
+    plotemit "$deftype:$vname:$expr"
 }
 
 function def() {
     isplot || return
-    emitdef DEF "$@"
+    plotemitdef DEF "$@"
 }
 
 function list() {
     isplot || return
-    emitdef CDEF "$@"
+    plotemitdef CDEF "$@"
 }
 
 function val() {
     isplot || return
-    emitdef VDEF "$@"
+    plotemitdef VDEF "$@"
 }
 
 function putstr() {
     isplot || return
-    emit "COMMENT:$*"
+    plotemit "COMMENT:$*"
 }
 
 function putstrln() {
     isplot || return
-    emit "COMMENT:$*"'\\n'
+    plotemit "COMMENT:$*"'\\n'
 }
 
 function plot() {
@@ -232,27 +446,58 @@ function plot() {
     local buf
     case "$shape" in
         LINE)
-            buf="LINE$width::";;
+            buf="LINE$width::"
+            ;;
         AREA)
             buf="AREA::"
             ;;
     esac
 
-    emit "$buf:$*"
+    plotemit "$buf:$*"
 }
 
 function gprint() {
     isplot || return
     local varspec="$1"
     local mesg="$2"
-    emit "GPRINT:$varspec:$mesg"
+    plotemit "GPRINT:$varspec:$mesg"
 }
 
 function gprintln() {
     isplot || return
     local varspec="$1"
     local mesg="$2"
-    emit "GPRINT:$varspec:$mesg"'\\n'
+    plotemit "GPRINT:$varspec:$mesg"'\\n'
+}
+
+##
+# on EVENT ACTION ...
+# return: 0 if success, otherwise illegal arguments.
+#   env EVENT = The event name, or duration (with unit).
+#   env ACTION = (action-args)
+#   env NEXT_ON = The index of next occurrence of "on", or to the end.
+function parse_event() {
+    [ $# = 0 ] && return 1
+
+    [ "$1" = 'on' ] || die "Illegal syntax, expected 'on': $*"
+    [ $# -lt 3 ] &&  die "Too few arguments for on-statement: $*"
+
+    EVENT="$2"
+    ACTION=()
+    NEXT_ON=$#
+
+    local i
+    local n=0
+    for ((i = 3; i <= $#; i++)); do
+        if [ "${!i}" = on ]; then
+            NEXT_ON=$((i - 1))
+            break
+        else
+            ACTION[n++]="${!i}"
+        fi
+    done
+
+    return 0
 }
 
 function rpn_eval() {
