autofill-control, and print more logs

diff --git a/uni/package/cooldeb/newdeb b/uni/package/cooldeb/newdeb
--- a/uni/package/cooldeb/newdeb
+++ b/uni/package/cooldeb/newdeb
@@ -59,22 +59,16 @@ function setopt() {
 }
 
 function main() {
-    if [ -z "$1" ]; then
-        echo "PACKAGE-NAME isn't specified. "
-        exit 1
-    fi
+    [ -z "$1" ] && die "PACKAGE-NAME isn't specified. "
+    [ -n "${1//[0-9a-zA-Z\-_]}" ] && die "Invalid package name: $1"
 
-    if [ -n "${1//[0-9a-zA-Z\-_]}" ]; then
-        echo "Invalid package name: $1"
-        exit 1
-    fi
     name=$1
-
     if [ -d "$name" ] && [ "$force" != 1 ]; then
-        echo "Directory $name/ is already existed. "
+        die "Directory $name/ is already existed. "
         exit 1
     fi
-    mkdir $name
+    _log1 "Create new Debian package: $name"
+    mkdir $name || die "Failed to create $name/"
 
     if [ "$versioned" = 1 ]; then
         if ! svn info >/dev/null 2>&1; then
@@ -86,26 +80,32 @@ function main() {
         svn ps svn:ignore '*.gz' $name
     fi
 
-    cd $name
+    _log2 "Enter $name/"
+    cd $name || die "Failed to chdir to $name/"
+
     if [ "$autotools" = 1 ]; then
-        autoinit
-        vercomp -i minor
+        _log1 "Create initial configurations for autotools"
+        autoinit || die "autoinit failed. "
     else
-        verinit
+        _log1 "Initialize version (only)"
+        verinit || die "verinit failed. "
     fi
+    _log2 "Increase the initial minor version"
+    vercomp -i minor
 
-    if [ "$prepost" = 1 ]; then
 
-        if [ "$autotools" = 1 ]; then
-            for pf in postinst.in prerm.in; do
-                echo "#!/bin/sh" >$pf
-                echo "# master-file" >>$pf
-                echo "" >>$pf
-                echo "echo \"$name - $pf ...\"" >>$pf
-            done
-            chmod a+x p*.in
+    if [ "$autotools" = 1 ] && [ "$prepost" = 1 ]; then
+        _log1 "Create pre/post scripts for autotools"
 
-            cat <<EOT >>Makefile.am
+        for pf in postinst.in prerm.in; do
+            echo "#!/bin/sh" >$pf
+            echo "# master-file" >>$pf
+            echo "" >>$pf
+            echo "echo \"$name - $pf ...\"" >>$pf
+        done
+        chmod a+x p*.in
+
+        cat <<EOT >>Makefile.am
 setup_SCRIPTS = \\
     postinst \\
     prerm
@@ -120,21 +120,25 @@ CLEANFILES = \${setup_SCRIPTS}
 	\$(do_subst) <\$< >\$@
 	chmod -w "\$@"
 EOT
-
-        fi #autotools
-    fi #prepost
+    fi
 
     if [ "$versioned" = 1 ]; then
+        _log1 "Add the fundamental files to VCS"
         svn add *
     fi
 
+    _log1 "Invoke dh_make with dirname renamed to -ver (temporary)"
     . dh_make-autover --createorig
 
+    _log1 "Remove any -*.orig backups generated by dh_make"
     # if [ "$keep_orig" != 1 ]; then
     rm -fR ../$name-0.*.orig
 
+    _log1 "Prepare files for debian/"
     cd debian
         if [ "$prepost" = 1 ]; then
+            _log2 "    Prepare prerm/postinst"
+
             mv postinst.ex postinst
             mv prerm.ex    prerm
 
@@ -148,34 +152,45 @@ EOT
                 echo \"        /usr/share/setup/$name/prerm\"; \
                 cat"
 
+            _log3 "    Make prerm/postinst executable"
             chmod a+x postinst prerm
         fi
 
         vi control
 
-        # source/quilt is not used.
-        rm -fr source/
+        if [ -d source ]; then
+            _log3 "    Remove unused source/"
+            # source/quilt is not used.
+            rm -fr source/
+        fi
 
+        _log2 "Leave $name/"
         cd ..
 
+    _log1 "Fill debian/control with uni-specific values"
+    autofill-control
 
     if [ "$versioned" = 1 ]; then
-        _log2 "Add special files under debian/ to svn"
+        _log1 "Prepare to commit debian/"
+
+        _log2 "    Add special files under debian/ to VCS"
         svn add --depth empty debian
 
-        # ignore debian/* by default.
+        _log2 "    Ignore debian/* by default. "
         svn ps svn:ignore '*' debian
 
+        _log2 "    Add fundamental debian/ control files"
         svn add debian/control
         svn add debian/postinst
         svn add debian/prerm
         svn add debian/docs
 
-        _log2 "Commit the initial version"
-        svn ci -m "New $name package initialized by newdeb"
+        _log2 "    Commit the initial version"
+        svn ci -m "$name package created by newdeb"
     fi
 
     if [ "$autotools" = 1 ]; then
+        _log1 "Initial build with autotools"
         autoreconf2 -is
         makelook
     fi
