show log/warn/error with color.

diff --git a/uni/xjl-bash-shlib/shlib.d/cliboot b/uni/xjl-bash-shlib/shlib.d/cliboot
--- a/uni/xjl-bash-shlib/shlib.d/cliboot
+++ b/uni/xjl-bash-shlib/shlib.d/cliboot
@@ -32,24 +32,22 @@ function do_arg() {
 }
 
 function quit() {
-    local EXITSTATUS=$?
+    local err=$?
     cleanup
     if [ $# != 0 ]; then
-        echo "$*"
+        if [ $err = 0 ]; then
+            _warn "$@"
+        else
+            _error "$@"
+        fi
     fi
-    exit $EXITSTATUS
+    exit $err
 }
 
 function die() {
-    local err
-    err=${2:-1}
-    if [ $err -ne 0 ]; then
-        _log1 "failed: $1"
-    else
-        _log2 "$1"
-    fi
+    _error "$@"
     cleanup
-    exit $err
+    exit 1
 }
 
 function bootvoid() {
@@ -67,7 +65,7 @@ function boot() {
                         -o "$short_opts" \
                         -l "$long_opts" \
                         -n "$BASENAME" -- "$@"`; then
-            # echo "Syntax error."
+            die "Syntax error."
             exit 1
         fi
 
diff --git a/uni/xjl-bash-shlib/shlib.d/log b/uni/xjl-bash-shlib/shlib.d/log
--- a/uni/xjl-bash-shlib/shlib.d/log
+++ b/uni/xjl-bash-shlib/shlib.d/log
@@ -1,3 +1,13 @@
+LOGFX=1
+LOGFX_INFO='[1;34m'
+LOGFX_INFO2='[34m'
+LOGFX_DEBUG='[37m'
+LOGFX_WARN='[1;45m'
+LOGFX_ERROR='[1;41m'
+
+LOGLEVEL_WARN=0
+LOGLEVEL_ERROR=-1
+
 if [ -z "$LOGLEVEL" ]; then
     LOGLEVEL=1
 fi
@@ -9,9 +19,41 @@ else
 fi
 
 function _log() {
+    local fx_=
+    local _fx=
     if [ $LOGLEVEL -ge $1 ]; then
+        if [ "$LOGFX" = 1 ]; then
+            _fx="[0m"
+            if [ $1 -le 1 ]; then
+                fx_="$LOGFX_INFO"
+            elif [ $1 = 2 ]; then
+                fx_="$LOGFX_INFO2"
+            else
+                fx_="$LOGFX_DEBUG"
+            fi
+        fi
         shift
-        echo "$LOGPREFIX$@" >&2
+        echo "$fx_$LOGPREFIX$@$_fx" >&2
+    fi
+}
+
+function _warn() {
+    if [ $LOGLEVEL -ge $LOGLEVEL_WARN ]; then
+        if [ $LOGFX = 1 ]; then
+            echo "$LOGFX_WARN$LOGPREFIX$@[0m" >&2
+        else
+            echo "$LOGPREFIX$@" >&2
+        fi
+    fi
+}
+
+function _error() {
+    if [ $LOGLEVEL -ge $LOGLEVEL_ERROR ]; then
+        if [ $LOGFX = 1 ]; then
+            echo "$LOGFX_ERROR$LOGPREFIX$@[0m" >&2
+        else
+            echo "$LOGPREFIX$@" >&2
+        fi
     fi
 }
 
@@ -24,7 +66,7 @@ function _sig() {
         if [ ${#line} -lt 80 ]; then
             line="$line${LINEPAD:0:$((80-${#line}))}"
         fi
-        echo -n "$line"$'\r' >&2
+        echo -en "$line"$'\r' >&2
     fi
 }
 
