Install archiva done.

diff --git a/uni/alt/archiva/postinst.in b/uni/alt/archiva/postinst.in
--- a/uni/alt/archiva/postinst.in
+++ b/uni/alt/archiva/postinst.in
@@ -1,4 +1,75 @@
-#!/bin/sh
-# master-file
+#!/bin/bash
+    . shlib-import cliboot
 
-echo "archiva - postinst.in ..."
+    RCSID='$Id: bash.sh 2255 2011-01-01 06:58:58Z lenik $'
+    short_opts="hqv"
+    long_opts="help,quiet,verbose,version"
+
+    LOGLEVEL=2
+
+function version() {
+    parse_id "$RCSID"
+    echo "[$BASENAME] Install archiva on jetty"
+    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
+}
+
+function help() {
+    version
+    echo
+    echo "Syntax: "
+    echo "    $0 [OPTION] [--] ..."
+    echo
+    echo "Options: "
+    echo "    -q, --quiet             Repeat to get less info"
+    echo "    -v, --verbose           Repeat to get more info"
+    echo "    -h, --help              Show this help page"
+    echo "        --version           Print the version info"
+}
+
+function setopt() {
+    case "$1" in
+        -h|--help)
+            help; exit;;
+        -q|--quiet)
+            LOGLEVEL=$((LOGLEVEL - 1));;
+        -v|--verbose)
+            LOGLEVEL=$((LOGLEVEL + 1));;
+        --version)
+            version; exit;;
+        *)
+            quit "invalid option: $1";;
+    esac
+}
+
+function main() {
+
+    _log1 "Config apache to forward archiva"
+
+        a2enmod proxy
+        a2enmod proxy_http
+        a2enmod rewrite
+        a2reload
+
+    download_archiva
+}
+
+function download_archiva() {
+    _log1 "Search and download Archiva WAR"
+    index=http://archiva.apache.org/download.html
+
+    _log2 "Parse index-1: $index"
+    index2=`grepurl -Em1 '[^"]+\.war' $index` || die "Index-1 parse error"
+
+    _log2 "Parse index-2: $index2"
+    war_url=`grepurl -Em1 '[^"]+\.war' $index2` || die "Index-2 parse error"
+
+    _log2 "Download $war_url..."
+    war_file=`wgetc $war_url` || die "Failed to download $war_url"
+
+    _log2 "Copy $war_file to @wardir@/archiva.war"
+    mkdir -p "@wardir@" || die "Couldn't create the directory @wardir@"
+    cp -f "$war_file" "@wardir@/archiva.war" || die "Failed to copy"
+}
+
+boot "$@"
+
