initial release.

diff --git a/uni/cdu-bodz-vol-dev/postinst.in b/uni/cdu-bodz-vol-dev/postinst.in
--- a/uni/cdu-bodz-vol-dev/postinst.in
+++ b/uni/cdu-bodz-vol-dev/postinst.in
@@ -1,4 +1,13 @@
 #!/bin/sh
 # master-file
 
-echo "cdu-bodz-vol-dev - postinst.in ..."
+echo "Config vol:bodzdev"
+
+install -d -m 2775 -g dev /mnt/bodzdev
+
+if ! mount-ebs bodzdev /mnt/bodzdev; then
+    echo "Failed to mount vol:bodzdev"
+    exit 1
+fi
+
+exit 0
