add echo-args for debug purpose.
rewrite eachdir by gen-bash.

diff --git a/uni/xjl-coolbash/eachdir b/uni/xjl-coolbash/eachdir
--- a/uni/xjl-coolbash/eachdir
+++ b/uni/xjl-coolbash/eachdir
@@ -1,17 +1,89 @@
 #!/bin/bash
+    RCSID='$Id: bash.sh 1432 2010-08-25 10:23:46Z lenik $'
+    short_opts="C:g:x:hqv"
+    long_opts="chdir,glob,exclude,help,quiet,verbose,version"
+    . /usr/lib/bash/cliboot
 
-for d in */; do
-    cd $d
+    LOGLEVEL=0
 
-    args=()
-    i=0
-    for arg in "$@"; do
-        arg="${arg//'{}'/$d}"
-        args[i]="$arg"
-        ((i++))
-    done
+    chdir=
+    glob='*'
+    exclude=
 
-    bash -c "${args[*]}"
+function version() {
+    parse_id "$RCSID"
+    echo "[$BASENAME] Execute commands in each dir"
+    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
+}
 
-    cd ..
-done
+function help() {
+    version
+    echo
+    echo "Syntax: "
+    echo "    $0 [OPTION] [--] COMMAND ARGS"
+    echo
+    echo "Options: "
+    echo "    -C, --chdir=DIR         chdir to DIR before enum dirs"
+    echo "    -g, --glob=GLOB         glob pattern to list dirs (default *)"
+    echo "    -x, --exclude=PATTERN   simple regex to exclude"
+    echo "    -q, --quiet             repeat to get less info"
+    echo "    -v, --verbose           repeat to get more info"
+    echo "    -h, --help              show this help page"
+    echo "        --version           print the version info"
+}
+
+function setopt() {
+    case "$1" in
+        -C|--chdir)
+            chdir="$2";;
+        -g|--glob)
+            glob="$2";;
+        -x|--exclude)
+            exclude="$2";;
+        -h|--help)
+            help; exit;;
+        -q|--quiet)
+            LOGLEVEL=$((LOGLEVEL - 1));;
+        -v|--verbose)
+            LOGLEVEL=$((LOGLEVEL + 1));;
+        --version)
+            version; exit;;
+        *)
+            quit "invalid option: $1";;
+    esac
+}
+
+function main() {
+    if [ -n "$chdir" ]; then
+        if ! cd $chdir; then
+            echo "Can't chdir to $chdir" >&2
+            exit 1
+        fi
+    fi
+
+    listfile=/tmp/eachdir-$$-$RANDOM
+    ls -d1 $glob/ >$listfile
+    while read dir; do
+        _log1 "$dir: "
+        if ! cd $dir; then
+            _log2 "    Failed to enter $dir, skipped"
+            continue
+        fi
+
+        args=()
+        i=0
+        for arg in "$@"; do
+            arg="${arg//'{}'/$dir}"
+            args[i]="$arg"
+            ((i++))
+        done
+
+        bash -c "${args[*]}"
+
+        cd ..
+    done <$listfile
+
+    rm -f $listfile
+}
+
+boot "$@"
