Add econf-*.

diff --git a/uni/toolenh/eclipse-enh/econf-save.in b/uni/toolenh/eclipse-enh/econf-save.in
--- a/uni/toolenh/eclipse-enh/econf-save.in
+++ b/uni/toolenh/eclipse-enh/econf-save.in
@@ -2,13 +2,12 @@
     . shlib-import cliboot
 
     RCSID='$Id: - @VERSION@ @DATE@ @TIME@ - $'
-    short_opts="fhqv"
-    long_opts="force,help,quiet,verbose,version"
-    force=0
+    short_opts="hqv"
+    long_opts="help,quiet,verbose,version"
 
 function version() {
     parse_id "$RCSID"
-    echo "[$BASENAME] Create 'symlink' for eclipse plugins"
+    echo "[$BASENAME] Save eclipse configuration"
     echo "Written by Lenik, Version $rcs_rev, Last updated at $rcs_date"
 }
 
@@ -16,23 +15,17 @@ function help() {
     version
     echo
     echo "Syntax: "
-    echo "    $0 [OPTION] [--] TARGET LINK-NAME"
+    echo "    $0 [OPTION] [--] ..."
     echo
     echo "Options: "
-    echo "    -f, --force             Force to overwrite"
     echo "    -q, --quiet             Repeat to get less info"
     echo "    -v, --verbose           Repeat to get more info"
     echo "    -h, --help              Show this help page"
     echo "        --version           Print the version info"
-    echo "Example: "
-    echo "  # eclipse-link ../lib/model-1.2.3 link/10model"
-    echo "    will create a file link/10model.link -> /opt/eclipse/lib/model-1.2.3"
 }
 
 function setopt() {
     case "$1" in
-        -f|--force)
-            force=1;;
         -h|--help)
             help; exit;;
         -q|--quiet)
@@ -47,26 +40,12 @@ function setopt() {
 }
 
 function main() {
-    if [ $# -lt 2 ]; then
-        help
-        exit
-    fi
 
-    target="$1"
-    link_name="$2"
-    link_file="$link_name.link"
-    if [ -e "$link_file" ]; then
-        if [ "$opt_force" = 1 ]; then
-            echo "$link_file is existed. "
-            exit 1
-        fi
-    fi
+    [ -x ./eclipse ] || die "Not in an eclipse home dir"
+    rm -f conf.rar || die "Failed to remove existing conf.rar"
 
-    #if [ "$canon" = 1 ]; then
-    target=`readlink -f "$target"`
-    #fi
-
-    echo "path=$target" >"$link_file"
+    rar a conf.rar artifacts.xml p2 configuration \
+        || die "Failed to create a rar archive"
 }
 
 boot "$@"
