coolcmd: ppid-closest print error to stdout, exit with error.

diff --git a/util/coolcmd/ppid-closest b/util/coolcmd/ppid-closest
--- a/util/coolcmd/ppid-closest
+++ b/util/coolcmd/ppid-closest
@@ -19,5 +19,6 @@
         pid=$ppid
     done
     
-    echo "failed to find the parent pid closest to $pattern."
-    
+    echo "failed to find the parent pid closest to $pattern." >&2
+    exit 1
+
