add shortcut -IKX for svn:ignore stuff.

diff --git a/uni/xjl-coolsvn/svnpsl b/uni/xjl-coolsvn/svnpsl
--- a/uni/xjl-coolsvn/svnpsl
+++ b/uni/xjl-coolsvn/svnpsl
@@ -1,11 +1,12 @@
 #!/bin/bash
     RCSID='$Id: bash.sh 1432 2010-08-25 10:23:46Z lenik $'
-    short_opts="sakdhqv"
-    long_opts="set,add,kill,diff,help,quiet,verbose,version"
+    short_opts="sakdIKXhqv"
+    long_opts="set,add,kill,diff,svn-ignore,svn-keywords,svn-externals,help,quiet,verbose,version"
     . /usr/lib/bash/cliboot
 
     mode=set
     diff=0
+    key=
 
 function version() {
     parse_id "$RCSID"
@@ -18,12 +19,16 @@ function help() {
     echo
     echo "Syntax: "
     echo "    svnpsl [OPTION] [--] PROPNAME PROPVAL... ; FILES"
+    echo "    svnpsl [OPTION] -I|-K|-X [--] PROPVAL... ; FILES"
     echo
     echo "Options: "
     echo "    -s, --set               set values (default)"
     echo "    -a, --add               add values"
     echo "    -k, --kill              delete values"
     echo "    -d, --diff              show diff of changes"
+    echo "    -I, --svn-ignore        operate on svn:ignore property"
+    echo "    -K, --svn-keywords      operate on svn:keywords property"
+    echo "    -X, --svn-externals     operate on svn:externals property"
     echo "    -q, --quiet             repeat to get less info"
     echo "    -v, --verbose           repeat to get more info"
     echo "    -h, --help              show this help page"
@@ -40,6 +45,12 @@ function setopt() {
             mode=delete;;
         -d|--diff)
             diff=1;;
+        -I|--svn-ignore)
+            key=svn:ignore;;
+        -K|--svn-keywords)
+            key=svn:keywords;;
+        -X|--svn-externals)
+            key=svn:externals;;
         -h|--help)
             help; exit;;
         -q|--quiet)
@@ -54,13 +65,15 @@ function setopt() {
 }
 
 function main() {
-    if [ -z "$1" ]; then
-        echo "Property name isn't specified. "
-        exit 1
-    fi
 
-    name="$1"
-    shift
+    if [ -z "$key" ]; then
+        if [ -z "$1" ]; then
+            echo "Property name isn't specified. "
+            exit 1
+        fi
+        key="$1"
+        shift
+    fi
 
     tmp_prefix=/tmp/svnprop-$$-$RANDOM
     tmp_vals=$tmp_prefix.vals
@@ -91,13 +104,13 @@ function main() {
             ;;
 
         add)
-            svn pg "$name" "$f" >$tmp_orig
+            svn pg "$key" "$f" >$tmp_orig
             cat $tmp_vals >>$tmp_orig
             sort -u $tmp_orig >$tmp_vals
             ;;
 
         delete)
-            svn pg "$name" "$f" | grep -vFf $tmp_vals >$tmp_orig
+            svn pg "$key" "$f" | grep -vFf $tmp_vals >$tmp_orig
             mv -f $tmp_orig $tmp_vals
             ;;
         esac
@@ -109,15 +122,15 @@ function main() {
         # echo '--- vals ---'; cat $tmp_vals; echo '------------'
 
         if [ "$diff" = 1 ]; then
-            svn pg "$name" "$f" | grep -v '^$' >$tmp_orig
+            svn pg "$key" "$f" | grep -v '^$' >$tmp_orig
             if diff -u $tmp_orig $tmp_vals; then
                 _log2 "    No changes, skipped"
                 continue
             fi
         fi
 
-        if ! svn ps -F $tmp_vals "$name" "$f"; then
-            echo "    Error set property $name on $f" >&2
+        if ! svn ps -F $tmp_vals "$key" "$f"; then
+            echo "    Error set property $key on $f" >&2
             exit 1
         fi
     done
