implemented fix-index

diff --git a/lenik/sbin/svn-dump b/lenik/sbin/svn-dump
--- a/lenik/sbin/svn-dump
+++ b/lenik/sbin/svn-dump
@@ -1,14 +1,20 @@
 #!/bin/bash
 
 stage=0
+cont=
 
 if [ "${1:0:1}" = : ]; then
     stage=${1#:}
     shift
 fi
 
+if [ "${1:0:1}" = '~' ]; then
+	cont="${1:1}"
+	shift
+fi
+
 if [ -z "$1" ]; then
-    echo svn-dump [:STAGE] REPO-DIR
+    echo svn-dump [:STAGE] [~continue-file] REPO-DIR
     exit 1
 fi
 
@@ -68,7 +74,40 @@ fi
 # fix revision if any... (not used)
 if [ $stage -le 3 ]; then
   echo 3. Reindex - fix revision
+    cd .reindex
+    for f in *; do
+        f_join=${f%%.*}
+        f_pack=${f#*.}
+        f_orig=${f_pack#*.}
+        f_pack=${f_pack%.*}
 
+        pack_maxvar=_packmax_$f_pack
+        pack_max=${!pack_maxvar}
+        if [ -z "$pack_max" ]; then pack_max=0; fi
+        if [ "$f_orig" -lt "$pack_max" ]; then
+            match_orig=
+            for ((i = f_orig + 1; i <= pack_max; i++)); do
+		for match in *.$f_pack.$i; do
+			if [ ! -f $match ]; then continue; fi
+                    match_join=${match%%.*}
+                    # match_orig=${match##*.}
+                    match_orig=$i
+                    mv $f $match_join.$f_pack.$f_orig
+			break 2
+                done
+            done
+            if [ -z "$match_orig" ]; then
+		echo "Can't find a insert point to move back a post-fix rev"
+		exit 1
+            fi
+            echo -n "<$f_pack.$f_orig -> $match_orig>"
+        else
+		eval "$pack_maxvar=$f_orig"
+		echo -n .
+        fi
+    done
+    echo
+    cd ..
 fi
 
 # prepare for merge, create empty dir-struct
@@ -89,6 +128,7 @@ fi
 if [ $stage -le 5 ]; then
   echo 5. Load
     for f in .reindex/*; do
+        if [ -n "$cont" -a "$f" \< "$cont" ]; then continue; fi
         s=${f##*/}
         newrev=${s%%.*}
         newrev=$((1$newrev-100000000+1))
@@ -102,11 +142,12 @@ if [ $stage -le 5 ]; then
             echo "Command: svnadmin load --parent-dir $module .merged <$f"
             exit 1
         fi
-        read current <.merged/db/current
-        if [ $newrev != $current ]; then
-            echo "Expect revision $newrev, but current is $current"
-            #exit 2
-        fi
+        # After reindex-fix, the joined revision is no more correct.
+        #read current <.merged/db/current
+        #if [ $newrev != $current ]; then
+        #    echo "$f: Expect revision $newrev, but current is $current"
+        #    #exit 2
+        #fi
     done
     echo
 fi
