tab/space review. always expand-tab in mixed-mode.

diff --git a/uni/xjl-cooldeb/dh_add_missing.in b/uni/xjl-cooldeb/dh_add_missing.in
--- a/uni/xjl-cooldeb/dh_add_missing.in
+++ b/uni/xjl-cooldeb/dh_add_missing.in
@@ -29,8 +29,8 @@ function help() {
 
 function setopt() {
     case "$1" in
-	-s|--symlink)
-		symlink=1;;
+        -s|--symlink)
+            symlink=1;;
         -h|--help)
             help; exit;;
         -q|--quiet)
@@ -45,19 +45,19 @@ function setopt() {
 }
 
 function main() {
-	if [ -z "$1" ]; then
-		if [ ! -d debian/ ]; then
-			echo "No debian/ directory. "
-			exit 1
-		fi
-	else
+    if [ -z "$1" ]; then
+        if [ ! -d debian/ ]; then
+            echo "No debian/ directory. "
+            exit 1
+        fi
+    else
         debiandir="$1"
     fi
-	debiandir="${debiandir%/}"
+    debiandir="${debiandir%/}"
 
     if ! cd "$debiandir"; then
-	echo "Failed to enter $debiandir"
-	exit 1
+        echo "Failed to enter $debiandir"
+        exit 1
     fi
 
     for defl in @DESTDIR@@debdefldir@/*; do
@@ -68,15 +68,15 @@ function main() {
             _log1 "Generate $basename"
 
             if [ $symlink = 1 ]; then
-		if ! ln -snf $defl $basename; then
-			echo "  failed to create symlink $basename -> $defl"
-			exit 1
-		fi
+                if ! ln -snf $defl $basename; then
+                    echo "  failed to create symlink $basename -> $defl"
+                    exit 1
+                fi
             else
-		if ! cp $defl $basename; then
-			echo "  failed to copy $defl"
-		    exit 1
-		fi
+                if ! cp $defl $basename; then
+                    echo "  failed to copy $defl"
+                    exit 1
+                fi
             fi
         fi
 
