transfer textp, binaryp, tourl from -coolbash.
new lineconf to do configuration by magic pattern.

diff --git a/uni/xjl-coolutils/sedit b/uni/xjl-coolutils/sedit
--- a/uni/xjl-coolutils/sedit
+++ b/uni/xjl-coolutils/sedit
@@ -1,7 +1,7 @@
 #!/bin/bash
     RCSID='$Id$'
-    short_opts="ci:dtmognhqv"
-    long_opts="stdout,replace,diff,keep-mode,keep-time,keep-owner,keep-group,dry-run,help,quiet,verbose,version"
+    short_opts="ci:dtmognehqv"
+    long_opts="stdout,replace,diff,keep-mode,keep-time,keep-owner,keep-group,dry-run,error-edit,help,quiet,verbose,version"
     . /usr/lib/bash/cliboot
 
     tee_output=
@@ -10,6 +10,7 @@
     keep_mode=
     keep_time=
     dry_run=
+    error_edit=
 
 function version() {
     parse_id "$RCSID"
@@ -32,6 +33,7 @@ function help() {
     echo "    -o, --keep-owner        keep file owner unchanged"
     echo "    -g, --keep-group        keep file group unchanged"
     echo "    -n, --dry-run           just for test, don't save the result"
+    echo "    -e, --error-edit        exit 1 if anything changed"
     echo "    -q, --quiet             repeat to get less info"
     echo "    -v, --verbose           repeat to get more info"
     echo "    -h, --help              show this help page"
@@ -61,6 +63,8 @@ function setopt() {
             keep_group=1;;
         -n|--dry-run)
             dry_run=1;;
+        -e|--error-edit)
+            error_edit=1;;
         -h|--help)
             help; exit;;
         -q|--quiet)
@@ -105,7 +109,10 @@ function main() {
 
     err=$?
 
-    if ! cmp -s "$file" "$buff"; then
+    cmp -s "$file" "$buff"
+    dirty=$?
+
+    if [ $dirty != 0 ]; then
         # contents changed
         if [ -n "$diff" ]; then
             $diff "$file" "$buff"
@@ -135,6 +142,10 @@ function main() {
     fi
 
     rm -f "$buff"
+
+    if [ "$error_edit" = 1 ] && [ "$dirty" = 1 ]; then
+        err=1
+    fi
 
     return $err
 }
