Bobup 2-stages support, -1 for gather, -2 for merge.

diff --git a/text/cooltext/bobup.in b/text/cooltext/bobup.in
--- a/text/cooltext/bobup.in
+++ b/text/cooltext/bobup.in
@@ -2,11 +2,13 @@
     . shlib-import cliboot
 
     RCSID='$Id: - @VERSION@ @DATE@ @TIME@ - $'
-    short_opts="e:s:hqv"
-    long_opts="editor:,suffix:,help,quiet,verbose,version"
+    short_opts="e:s:12hqv"
+    long_opts="editor:,suffix:,first-pass,second-pass,help,quiet,verbose,version"
 
     editor=$EDITOR
     suffix=
+    p1=0
+    p2=0
 
 function version() {
     parse_id "$RCSID"
@@ -23,6 +25,8 @@ function help() {
     echo "Options: "
     echo "    -e, --editor=EDITOR     Use specific editor"
     echo "    -s, --suffix=SUFFIX     Save each file with this suffix"
+    echo "    -1, --first-pass        Gather all files into a temp file but not edit/merge"
+    echo "    -2, --second-pass       Merge temp file into fs"
     echo "    -q, --quiet             Repeat to get less info"
     echo "    -v, --verbose           Repeat to get more info"
     echo "    -h, --help              Show this help page"
@@ -35,6 +39,10 @@ function setopt() {
             editor="$2";;
         -s|--suffix)
             suffix="$2";;
+        -1|--first-pass)
+            p1=1;;
+        -2|--second-pass)
+            p2=1;;
         -h|--help)
             help; exit;;
         -q|--quiet)
@@ -49,94 +57,120 @@ function setopt() {
 }
 
 function main() {
-    if [ $# != 1 ]; then
-        die "One and only one DIR must be specified."
+    if [ "$p1$p2" = 00 ]; then
+        p1=1
+        p2=1
     fi
 
-    if [ -z "$editor" ]; then
-        editor="$EDITOR"
-    fi
+    [ $# = 0 ] && set /dev/stdin
+    [ -z "$editor" ] && editor="$EDITOR"
 
-    DIR="$1"
-    DIR="${DIR%/}"/
+    if [ "$p1" = 0 ]; then
+        tmpf="$1"
+        [ -f "$tmpf" ] || die "Failed to open the temp file $tmpf"
+    else
+        tmpf=`tempfile` || die "Failed to create temp file"
 
-    tmpf=`tempfile` || die "Failed to create temporary file"
-
-    echo .DIR $DIR >>$tmpf
-    echo DATE `date` >>$tmpf
-    echo "-" >>$tmpf
-
-    while IFS= read file; do
-        base="${file##*/}"
-
-        if [ -n "$suffix" ]; then
-            if [ "${base: -${#suffix}}" = "$suffix" ]; then
-                _log2 "Skip file with suffix: $f"
-                continue
-            fi
-        fi
-
-        echo FILE "$file" >>$tmpf
-        echo DATE `stat -c %y "$f"` >>$tmpf
-        sed -e 's/^/  | /' "$f" >>$tmpf
+        echo .DIR "$PWD" >>$tmpf
+        echo DATE `date` >>$tmpf
         echo "---------------------------------------------------------------------" >>$tmpf
-    done
 
-    if ! "${editor[@]}" $tmpf; then
-        echo "Edit failed, see the temporary file $tmpf for recovery."
-        exit 1
+        for list in "$@"; do
+                if [ ! -r "$list" ]; then
+                        _warn "Can't read from list file $list, skipped"
+                        continue
+                fi
+
+                echo "Process list file $list"
+                while IFS= read file; do
+                        if [ -d "$file" ]; then
+                                _warn "Directory entry is skipped: $file"
+                                continue
+                        fi
+
+                        base="${file##*/}"
+
+                        if [ -n "$suffix" ]; then
+                                if [ "${base: -${#suffix}}" = "$suffix" ]; then
+                                        _log2 "Skip file with suffix: $f"
+                                        continue
+                                fi
+                        fi
+
+                        echo FILE "$file" >>$tmpf
+                        echo DATE `stat -c %y "$file"` >>$tmpf
+                        sed -e 's/^/  | /' "$file" >>$tmpf
+                        echo "---------------------------------------------------------------------" >>$tmpf
+                done <"$list"
+        done
     fi
 
-    _log1 "Batch update..."
+    case "$p1$p2" in
+    01)
+        _log1 "Batch updating with $tmpf..."
+        ;;
+    10)
+        _log1 "Please edit $tmpf and call $0 -2 $tmpf later."
+        ;;
+    11)
+        if ! "${editor[@]}" $tmpf; then
+            die "Edit failed, see the temporary file $tmpf for recovery."
+        fi
+        ;;
+    esac
 
-    cname=
-    cfile=
-    cfile_s=
-    ctmp=`tempfile`
-    cdate=
+    if [ "$p2" = 1 ]; then
+        cname=
+        cfile=
+        cfile_s=
+        ctmp=`tempfile`
+        cdate=
 
-    while IFS=$'\x1' read l; do
-        c4="${l:0:4}"
+        while IFS=$'\x1' read l; do
+            c4="${l:0:4}"
 
-        if [ "$c4" = '  | ' ]; then
-            if [ -z "$cfile" ]; then
-                _warn "Skipped content: $content"
+            if [ "$c4" = '  | ' ]; then
+                if [ -z "$cfile" ]; then
+                    _warn "Skipped content: $content"
+                    continue
+                fi
+
+                echo "$l" >>$ctmp
                 continue
             fi
 
-            echo "$l" >>$ctmp
-            continue
-        fi
+            param="${l:4}"
+            while [ "${param:0:1}" == ' ' ]; do
+                param="${param:1}"
+            done
 
-        param="${l:4}"
-        while [ "${param:0:1}" == ' ' ]; do
-            param="${param:1}"
-        done
+            case "$c4" in
+            '')
+                _warn "pure empty line occurred, skipped";;
+            -*)
+                continue;;
+            .*)
+                continue;;
+            FILE)
+                commit
+                #cfile="$DIR$param"
+                cfile="$param"
+                cfile_s="$cfile$suffix"
+                ;;
+            DATE)
+                cdate="$param";;
+            *)
+                _warn "Invalid C4 class: $c4"
+                ;;
+            esac
 
-        case "$c4" in
-        '')
-            _warn "pure empty line occurred, skipped";;
-        -*)
-            continue;;
-        .*)
-            continue;;
-        NAME)
-            commit
-            cfile="$DIR$param"
-            cfile_s="$cfile$suffix"
-            ;;
-        DATE)
-            cdate="$param";;
-        *)
-            _warn "Invalid C4 class: $c4"
-            ;;
-        esac
+        done <"$tmpf"
 
-    done <"$tmpf"
+        commit
 
-    commit
-
-    rm -f $tmpf
+        # Only clean immediately if p1p2=11
+        [ "$p1" = 1 ] && rm -f $tmpf
+    fi
 }
 
 function commit() {
