bobup add options: --timestamp, --out.

diff --git a/text/cooltext/bobup.in b/text/cooltext/bobup.in
--- a/text/cooltext/bobup.in
+++ b/text/cooltext/bobup.in
@@ -2,13 +2,15 @@
     . shlib-import cliboot
 
     RCSID='$Id: - @VERSION@ @DATE@ @TIME@ - $'
-    short_opts="e:s:12hqv"
-    long_opts="editor:,suffix:,first-pass,second-pass,help,quiet,verbose,version"
+    short_opts="e:s:t12o:hqv"
+    long_opts="editor:,suffix:,timestamp,first-pass,second-pass,out:,help,quiet,verbose,version"
 
     editor=$EDITOR
     suffix=
     p1=0
     p2=0
+    tmpout=
+    timestamp=0
 
 function version() {
     parse_id "$RCSID"
@@ -25,8 +27,10 @@ function help() {
     echo "Options: "
     echo "    -e, --editor=EDITOR     Use specific editor"
     echo "    -s, --suffix=SUFFIX     Save each file with this suffix"
+    echo "    -t, --timestamp         Include timestamp in the merged file"
     echo "    -1, --first-pass        Gather all files into a temp file but not edit/merge"
     echo "    -2, --second-pass       Merge temp file into fs"
+    echo "    -o, --out=FILE          Specify name of temp file"
     echo "    -q, --quiet             Repeat to get less info"
     echo "    -v, --verbose           Repeat to get more info"
     echo "    -h, --help              Show this help page"
@@ -39,10 +43,14 @@ function setopt() {
             editor="$2";;
         -s|--suffix)
             suffix="$2";;
+        -t|--timestamp)
+            timestamp=1;;
         -1|--first-pass)
             p1=1;;
         -2|--second-pass)
             p2=1;;
+        -o|--out)
+            tmpout="$2";;
         -h|--help)
             help; exit;;
         -q|--quiet)
@@ -69,11 +77,16 @@ function main() {
         tmpf="$1"
         [ -f "$tmpf" ] || die "Failed to open the temp file $tmpf"
     else
-        tmpf=`tempfile` || die "Failed to create temp file"
+        if [ -n "$out" ]; then
+            tmpf="$out"
+            echo -n >"$tmpf"
+        else
+            tmpf=`tempfile` || die "Failed to create temp file"
+        fi
 
         echo .DIR "$PWD" >>$tmpf
-        echo DATE `date` >>$tmpf
-        echo "---------------------------------------------------------------------" >>$tmpf
+
+        [ "$timestamp" = 1 ] && echo DATE `date` >>$tmpf
 
         for list in "$@"; do
                 if [ ! -r "$list" ]; then
@@ -97,10 +110,11 @@ function main() {
                                 fi
                         fi
 
-                        echo FILE "$file" >>$tmpf
-                        echo DATE `stat -c %y "$file"` >>$tmpf
-                        sed -e 's/^/  | /' "$file" >>$tmpf
                         echo "---------------------------------------------------------------------" >>$tmpf
+                        echo FILE "$file" >>$tmpf
+                        [ "$timestamp" = 1 ] && echo DATE `stat -c %y "$file"` >>$tmpf
+                        sed -e 's/^/  | /' "$file" >>$tmpf
+                        # echo >>$tmpf
                 done <"$list"
         done
     fi
@@ -113,7 +127,21 @@ function main() {
         _log1 "Please edit $tmpf and call $0 -2 $tmpf later."
         ;;
     11)
-        if ! "${editor[@]}" $tmpf; then
+        "${editor[@]}" $tmpf
+        err=$?
+
+        editor_name="${editor##*/}"
+        if [ "${editor_name:0:2}" = vi ]; then
+            if tty_reset=`which reset`; then
+                _log1 "TTY fixup for Vim editor"
+                tty
+
+                stty /dev/tty sane # not work here.
+                #reset
+            fi
+        fi
+
+        if [ $err != 0 ]; then
             die "Edit failed, see the temporary file $tmpf for recovery."
         fi
         ;;
@@ -146,7 +174,8 @@ function main() {
 
             case "$c4" in
             '')
-                _warn "pure empty line occurred, skipped";;
+                # _warn "pure empty line occurred, skipped"
+                ;;
             -*)
                 continue;;
             .*)
