search for alt-file: check if createable in the dir

diff --git a/uni/xjl-coolcmd/subst b/uni/xjl-coolcmd/subst
--- a/uni/xjl-coolcmd/subst
+++ b/uni/xjl-coolcmd/subst
@@ -87,7 +87,7 @@ function main() {
     fi
 
     if [ -z "$1" ]; then
-        echo "Keyword isn't specified. "
+        echo "Keyword isn't specified. " >&2
         return 1
     fi
 
@@ -102,14 +102,14 @@ function main() {
     keyword="$1"
     if [ "${keyword/:}" = "$keyword" ]; then
         if [ "$force" != 1 ]; then
-            echo "Warning: bare keyword without package name, use -f to override."
+            echo "Warning: bare keyword without package name, use -f to override." >&2
             return 1
         fi
     fi
 
     if [ "${keyword#*[}" != "$keyword" ]; then
         if [ "${keyword%]}" = "$keyword" ]; then
-            echo "Invalid keyword: '$keyword'"
+            echo "Invalid keyword: '$keyword'" >&2
             return 1
         fi
         attr="${keyword#*[}"
@@ -127,28 +127,41 @@ function main() {
     fi
     nalt=${#altfiles[@]}
     altindex=0
-    last=0
 
     for file in "${altfiles[@]}"; do
+        dir=${file%/*}
+        final=$((++altindex == nalt))
+
         if [ $mode != list ]; then
             if [ -z "$attr" ]; then attr=text; fi
 
-            if [ $last = 0 ] && ! grep -q "^$attr=" $file; then
-                # undefined attribute will try on the next alt.
-                continue
+            if [ $final = 0 ]; then
+                if [ -f $file ]; then
+                    if ! grep -q "^$attr=" $file; then # unmatched
+                        continue
+                    fi
+                    if [ ! -w "$file" ]; then # can't change file
+                        continue
+                    fi
+                else
+                    if [ ! -w "$dir" ]; then # can't create new file
+                        continue
+                    fi
+                fi
             fi
 
-            if [ -f "$file" ] && [ ! -w "$file" ]; then
-                if [ $last = 1 ]; then
-                    echo "File is not writable: $file"
+            if [ -f "$file" ]; then
+                if [ ! -w "$file" ]; then
+                    echo "File is not writable: $file" >&2
                     return 1
-                else
-                    continue # find next writable alt-file
+                fi
+            else
+                if [ ! -w "$dir" ]; then
+                    echo "Can't create new file in $dir" >&2
+                    return 1
                 fi
             fi
         fi
-
-        ((last = ++altindex == nalt))
 
         case $mode in
         list)
@@ -164,7 +177,6 @@ function main() {
             ;;
 
         add)
-            dir=${file%/*}
             if [ ! -d "$dir" ]; then
                 _log1 "Create new package dir $dir"
                 mkdir -p "$dir"
